#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "molokai"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"
enable_vimfiler_filetypeicon = true
enable_tabline_filetype_icon = true
statusline_separator = "arrow"
default_indent = 8
expand_tab = true
enable_projects_cache = true
projects_cache_num = 50

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
autocomplete_method = "deoplete"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "format"
format_method = "neoformat"
format_on_save = true

[[layers]]
name = "git"
git_plugin = "fugitive"

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
enable_clang_syntax_highlight = false

[[layers]]
name = "lang#python"
python_interpreter = "/usr/bin/python"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#assembly"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#jsonet"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#html"

#it is crucial that telescope is after fzf
[[layers]]
name="fzf"

[[layers]]
name = "telescope"

[[layers]]
name = "colorscheme"

[[layers]]
name = "shell"

[[layers]]
name = "treesitter"

[[layers]]
name = "tools"

[[custom_plugins]]
repo ="jasonccox/vim-wayland-clipboard"

[[layers]]
name = "lsp"
#nvim
enabled_clients = ["rust_analyzer", "pylsp", "clangd", "tsserver", "htmlls", "cssls", "dockerls", "java_language_server", "ruby_ls"]
#vim
filetypes = ["rust", "python", "javascript", "typescript", "typescriptreact", "svelte"]

[layers.override_cmd]
rust=["rust-analyzer"]
