#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "molokai"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = true
bootstrap_before = "myspacevim#before"
bootstrap_after = "myspacevim#after"
enable_vimfiler_filetypeicon = true
statusline_separator = "arrow"
default_indent = 8
expand_tab = true
enable_projects_cache = true
projects_cache_num = 50
sidebar_width=40

[[layers]]
name = "core"
enable_filetree_gitstatus=true

# Enable autocomplete layer
[[layers]]
name = "autocomplete"
autocomplete_method = "deoplete"
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "format"
format_method = "neoformat"
format_on_save = true

[[layers]]
name = "git"
git_plugin = "fugitive"

[[layers]]
name = "lang#c"
clang_executable = "/usr/bin/clang"
enable_clang_syntax_highlight = false

[[layers]]
name = "lang#python"
python_interpreter = "/usr/bin/python"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#assembly"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#jsonet"

[[layers]]
name = "lang#rust"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#ipynb"

[[layers]]
name = "lang#lua"

#it is crucial that telescope is after fzf
[[layers]]
name="fzf"

[[layers]]
name = "telescope"

[[layers]]
name = "colorscheme"

[[layers]]
name = "shell"

[[layers]]
name = "treesitter"

[[layers]]
name = "tools"

[[layers]]
name="debug"

[[layers]]
name="sudo"

[[custom_plugins]]
repo ="jasonccox/vim-wayland-clipboard"

[[custom_plugins]]
repo="ryanoasis/vim-devicons"

[[custom_plugins]]
repo="MunifTanjim/nui.nvim"


[[custom_plugins]]
name = "jackMort/ChatGPT.nvim"
#  merged = false

#what do I need?
#  [custom_plugins.location]
#    scheme = "https"
#    domain = "github.com"
#    owner = "jackMort"
#    repo = "ChatGPT.nvim.git"
#
#  hook_add = '''
#    function! ChatGPTSetup() abort
#        call dein#set_var('chatgpt#config', {'my_api_key': 'aoeuaoeu'})
#    endfunction
#
#    function! Config() abort
#        call ChatGPTSetup()
#    endfunction
#  '''
#
#  depends = ["nui.nvim", "plenary.nvim", "telescope.nvim"]


[[layers]]
name = "lsp"
#nvim
enabled_clients = ["jdtls", "rust_analyzer", "pylsp", "clangd", "tsserver", "html", "cssls", "dockerls","ruby_ls", "vimls"]
#vim
filetypes = ["c", "rust", "python", "javascript", "typescript", "typescriptreact", "svelte" ]

[layers.override_client_cmds]
    jdtls = ["jdtls", "-configuration", "~/.cache/jdtls/config", "-data", "~/.cache/jdtls/workspace"]
