[cargo-build]
    command = 'cargo build'
    isBackground = true
[cargo-debug]
    command = 'cargo run build'
[docker-dev]
    command = 'docker compose up --build'
    isBackground = true
[docker-stop]
    command = 'docker compose down'
[k8s-all]
    command = 'kubectl apply -f ${workspaceFolder}/k8s'
[minikube-start]
    command = 'minikube start'
    isBackground = true
[minikube-stop]
    command = 'minikube stop'
    isBackground = true
